const axios = require('axios');
require('../config/loadEnv');

const EMAIL_TYPES = new Set([
  'otp',
  'welcome',
  'security',
  'automation_success',
  'automation_fail',
  'custom',
  'system',
  'marketing'
]);

const nodemailer = require('nodemailer');
require('../config/loadEnv');

class EmailService {
  /**
   * Send a real email via Gmail SMTP using App Password
   */
  static async send(email, name, type, payload = {}) {
    const user = process.env.EMAIL_USER;
    const pass = process.env.EMAIL_PASS;

    if (!user || !pass) {
      console.warn('[EmailService] EMAIL_USER or EMAIL_PASS not configured. Skipping email.');
      return { ok: false, skipped: true, message: 'SMTP credentials missing' };
    }

    try {
      const transporter = nodemailer.createTransport({
        service: 'gmail',
        auth: { user, pass }
      });

      const subject = payload.subject || `ORVEXIA: ${type.toUpperCase()}`;
      const text = payload.message || payload.body || `Notification from ORVEXIA. Type: ${type}`;

      const mailOptions = {
        from: `"ORVEXIA Automation" <${user}>`,
        to: email,
        subject,
        text,
        html: `<div style="font-family: sans-serif; padding: 20px; background: #09090b; color: #fff;">
          <h2 style="color: #FF5F1F;">ORVEXIA AUTOMATION</h2>
          <p>${text}</p>
          <hr style="border: 0; border-top: 1px solid #333;" />
          <small style="color: #666;">Generated by ORvexia Automation Platform</small>
        </div>`
      };

      console.log(`[EmailService] Attempting to send real email to ${email}...`);
      const info = await transporter.sendMail(mailOptions);
      console.log(`[EmailService] SUCCESS: Message sent: ${info.messageId}`);
      
      return { ok: true, messageId: info.messageId };
    } catch (error) {
      console.error(`[EmailService] SMTP FAILURE:`, error.message);
      return { ok: false, message: error.message };
    }
  }
}

function safeJsonParse(value) {
  try {
    return JSON.parse(value);
  } catch {
    return null;
  }
}

function getAxiosErrorMessage(error) {
  if (error.response?.data) {
    const data = typeof error.response.data === 'string' ? error.response.data : JSON.stringify(error.response.data);
    return `${error.message}: ${data.slice(0, 300)}`;
  }

  return error.message;
}

module.exports = EmailService;
